Traceback (most recent call last):
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from numba import jit
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mImportError[0m                               Traceback (most recent call last)
Cell [1;32mIn[93], line 1[0m
[1;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mnumba[39;00m [38;5;28;01mimport[39;00m jit

File [1;32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\numba\__init__.py:59[0m
[0;32m     54[0m             msg [38;5;241m=[39m ([38;5;124m"[39m[38;5;124mNumba requires SciPy version 1.0 or greater. Got SciPy [39m[38;5;124m"[39m
[0;32m     55[0m                    [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mscipy[38;5;241m.[39m__version__[38;5;132;01m}[39;00m[38;5;124m.[39m[38;5;124m"[39m)
[0;32m     56[0m             [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(msg)
[1;32m---> 59[0m [43m_ensure_critical_deps[49m[43m([49m[43m)[49m
[0;32m     60[0m [38;5;66;03m# END DO NOT MOVE[39;00m
[0;32m     61[0m [38;5;66;03m# ---------------------- WARNING WARNING WARNING ----------------------------[39;00m
[0;32m     64[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01m_version[39;00m [38;5;28;01mimport[39;00m get_versions

File [1;32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\numba\__init__.py:45[0m, in [0;36m_ensure_critical_deps[1;34m()[0m
[0;32m     42[0m [38;5;28;01mif[39;00m numpy_version [38;5;241m>[39m ([38;5;241m2[39m, [38;5;241m0[39m):
[0;32m     43[0m     msg [38;5;241m=[39m ([38;5;124mf[39m[38;5;124m"[39m[38;5;124mNumba needs NumPy 2.0 or less. Got NumPy [39m[38;5;124m"[39m
[0;32m     44[0m            [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mnumpy_version[[38;5;241m0[39m][38;5;132;01m}[39;00m[38;5;124m.[39m[38;5;132;01m{[39;00mnumpy_version[[38;5;241m1[39m][38;5;132;01m}[39;00m[38;5;124m.[39m[38;5;124m"[39m)
[1;32m---> 45[0m     [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(msg)
[0;32m     47[0m [38;5;28;01mtry[39;00m:
[0;32m     48[0m     [38;5;28;01mimport[39;00m [38;5;21;01mscipy[39;00m

[1;31mImportError[0m: Numba needs NumPy 2.0 or less. Got NumPy 2.2.

