Traceback (most recent call last):
  File "C:\Users\janko\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\janko\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\janko\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\janko\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\janko\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\janko\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\janko\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\janko\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Re≈°imo sistem
P = np.linalg.solve(A, b)
P
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mUFuncTypeError[0m                            Traceback (most recent call last)
Input [1;32mIn [10][0m, in [0;36m<cell line: 2>[1;34m()[0m
[0;32m      1[0m [38;5;66;03m# Re≈°imo sistem[39;00m
[1;32m----> 2[0m P [38;5;241m=[39m [43mnp[49m[38;5;241;43m.[39;49m[43mlinalg[49m[38;5;241;43m.[39;49m[43msolve[49m[43m([49m[43mA[49m[43m,[49m[43m [49m[43mb[49m[43m)[49m
[0;32m      3[0m P

File [1;32m<__array_function__ internals>:180[0m, in [0;36msolve[1;34m(*args, **kwargs)[0m

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\linalg\linalg.py:400[0m, in [0;36msolve[1;34m(a, b)[0m
[0;32m    398[0m signature [38;5;241m=[39m [38;5;124m'[39m[38;5;124mDD->D[39m[38;5;124m'[39m [38;5;28;01mif[39;00m isComplexType(t) [38;5;28;01melse[39;00m [38;5;124m'[39m[38;5;124mdd->d[39m[38;5;124m'[39m
[0;32m    399[0m extobj [38;5;241m=[39m get_linalg_error_extobj(_raise_linalgerror_singular)
[1;32m--> 400[0m r [38;5;241m=[39m [43mgufunc[49m[43m([49m[43ma[49m[43m,[49m[43m [49m[43mb[49m[43m,[49m[43m [49m[43msignature[49m[38;5;241;43m=[39;49m[43msignature[49m[43m,[49m[43m [49m[43mextobj[49m[38;5;241;43m=[39;49m[43mextobj[49m[43m)[49m
[0;32m    402[0m [38;5;28;01mreturn[39;00m wrap(r[38;5;241m.[39mastype(result_t, copy[38;5;241m=[39m[38;5;28;01mFalse[39;00m))

[1;31mUFuncTypeError[0m: Cannot cast ufunc 'solve1' input 0 from dtype('O') to dtype('float64') with casting rule 'same_kind'
UFuncTypeError: Cannot cast ufunc 'solve1' input 0 from dtype('O') to dtype('float64') with casting rule 'same_kind'

