Traceback (most recent call last):
  File "C:\Users\janko\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\janko\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\janko\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\janko\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\janko\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\janko\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\janko\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\janko\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pip
#moduli_vsi = {print(i.key) for i in pip.get_installed_distributions()}

moduli_vsi = {i.key: i.version for i in pip.get_installed_distributions()}

moduli_vsi

------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mAttributeError[0m                            Traceback (most recent call last)
Input [1;32mIn [1][0m, in [0;36m<cell line: 4>[1;34m()[0m
[0;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpip[39;00m
[0;32m      2[0m [38;5;66;03m#moduli_vsi = {print(i.key) for i in pip.get_installed_distributions()}[39;00m
[1;32m----> 4[0m moduli_vsi [38;5;241m=[39m {i[38;5;241m.[39mkey: i[38;5;241m.[39mversion [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m [43mpip[49m[38;5;241;43m.[39;49m[43mget_installed_distributions[49m()}
[0;32m      6[0m moduli_vsi

[1;31mAttributeError[0m: module 'pip' has no attribute 'get_installed_distributions'
AttributeError: module 'pip' has no attribute 'get_installed_distributions'

