Traceback (most recent call last):
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_core\utils\__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_core\utils\__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\janko\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
optimize.bisect(f, -2, 5, xtol=1e-3)  
------------------


[31m---------------------------------------------------------------------------[39m
[31mValueError[39m                                Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[9][39m[32m, line 1[39m
[32m----> [39m[32m1[39m [43moptimize[49m[43m.[49m[43mbisect[49m[43m([49m[43mf[49m[43m,[49m[43m [49m[43m-[49m[32;43m2[39;49m[43m,[49m[43m [49m[32;43m5[39;49m[43m,[49m[43m [49m[43mxtol[49m[43m=[49m[32;43m1e-3[39;49m[43m)[49m  

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\scipy\optimize\_zeros_py.py:595[39m, in [36mbisect[39m[34m(f, a, b, args, xtol, rtol, maxiter, full_output, disp)[39m
[32m    593[39m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([33mf[39m[33m"[39m[33mrtol too small ([39m[38;5;132;01m{[39;00mrtol[38;5;132;01m:[39;00m[33mg[39m[38;5;132;01m}[39;00m[33m < [39m[38;5;132;01m{[39;00m_rtol[38;5;132;01m:[39;00m[33mg[39m[38;5;132;01m}[39;00m[33m)[39m[33m"[39m)
[32m    594[39m f = _wrap_nan_raise(f)
[32m--> [39m[32m595[39m r = [43m_zeros[49m[43m.[49m[43m_bisect[49m[43m([49m[43mf[49m[43m,[49m[43m [49m[43ma[49m[43m,[49m[43m [49m[43mb[49m[43m,[49m[43m [49m[43mxtol[49m[43m,[49m[43m [49m[43mrtol[49m[43m,[49m[43m [49m[43mmaxiter[49m[43m,[49m[43m [49m[43margs[49m[43m,[49m[43m [49m[43mfull_output[49m[43m,[49m[43m [49m[43mdisp[49m[43m)[49m
[32m    596[39m [38;5;28;01mreturn[39;00m results_c(full_output, r, [33m"[39m[33mbisect[39m[33m"[39m)

[31mValueError[39m: f(a) and f(b) must have different signs

